ignore:
  - .venv/*
  - .pytest_cache/*
  - .vscode/*
  - htmlcov/*
  - logs/*
  - media/*
  - node_modules/*
  - scss/*
  - static/*
  - staticfiles/*

refactor:
  skip: []

github:
  labels: []
  ignore_labels:
    - sourcery-ignore
  sourcery_branch: sourcery/{base_branch}
